version: '3.8'

x-app: &app
  environment: &env
    NODE_ENV: ${NODE_ENV:-production}
    RAILS_ENV: ${RAILS_ENV:-production}
    RAILS_SERVE_STATIC_FILES: 1
    RAILS_LOG_TO_STDOUT: 1
  image: gcr.io/opencspm/engine:0.1.23
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - core:/app
    - ../assets:/app/data
    - ../config:/app/load_config
    - ../../opencspm-controls:/app/controls/
    - .dockerdev/.psqlrc:/app/.psqlrc:ro
    - .dockerdev/.bashrc:/app/.bashrc:ro
  environment:
    <<: *env
    REDIS_URL: redis://redis:6379/
    DATABASE_URL: postgres://postgres:postgres@db:5432
    BOOTSNAP_CACHE_DIR: /gems/_bootsnap
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vi
    MALLOC_ARENA_MAX: 2
  depends_on:
    - db
    - redis

services:
  core:
    <<: *backend
    hostname: core
    command: ./init.sh
    ports:
      - '5000:5000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://65.21.250.114:5000/healthz']
      interval: 5s
      timeout: 5s
      retries: 11

  worker:
    <<: *backend
    hostname: worker
    command: bundle exec sidekiq -C config/sidekiq.yml
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pgrep', '-x', 'bundle']
      interval: 10s
      retries: 3
    depends_on:
      - core
      - db
      - redis

  db:
    image: gcr.io/opencspm/postgres:13.2
    hostname: db
    volumes:
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: gcr.io/opencspm/redisgraph:edge-0.0.1
    hostname: redis
    volumes:
      - redis:/data
    ports:
      - 6379
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 2s
      timeout: 3s
      retries: 30

volumes:
  core:
  postgres:
  redis:
