---
- id: gce-1
  resource: compute.googleapis.com/projects/demo1-bad/zones/us-central1-a/instances/dev-secrets-manager
  status: passed
  profile: gcp-cis-gcp-1.1
- id: gce-1
  resource: compute.googleapis.com/projects/demo1-good/zones/us-central1-a/instances/dev-secrets-manager
  status: passed
  profile: gcp-cis-gcp-1.1
- id: gce-2
  resource: compute.googleapis.com/projects/demo1-bad/zones/us-central1-a/instances/dev-secrets-manager
  status: failed
  profile: gcp-cis-gcp-1.1
- id: gce-2
  resource: compute.googleapis.com/projects/demo1-good/zones/us-central1-a/instances/dev-secrets-manager
  status: failed
  profile: gcp-cis-gcp-1.1
- id: gce-3
  resource: compute.googleapis.com/projects/demo1-bad/zones/us-central1-a/instances/dev-secrets-manager
  status: failed
  profile: gcp-cis-gcp-1.1
- id: gce-3
  resource: compute.googleapis.com/projects/demo1-good/zones/us-central1-a/instances/dev-secrets-manager
  status: failed
  profile: gcp-cis-gcp-1.1
- id: iam-1
  resource: The Organization
  status: passed
  profile: gcp-cis-gcp-1.1
- id: iam-2
  resource: The Organization
  status: passed
  profile: gcp-cis-gcp-1.1
- id: gke-1
  resource: container.googleapis.com/projects/demo1-bad/locations/us-central1/clusters/prod-cluster1
  status: failed
  profile: gcp-cis-gke-1.1
- id: gke-1
  resource: container.googleapis.com/projects/demo1-good/locations/us-central1/clusters/prod-cluster1
  status: passed
  profile: gcp-cis-gke-1.1
- id: gke-2
  resource: container.googleapis.com/projects/demo1-bad/locations/us-central1/clusters/prod-cluster1
  status: failed
  profile: gcp-cis-gke-1.1
- id: gke-2
  resource: container.googleapis.com/projects/demo1-good/locations/us-central1/clusters/prod-cluster1
  status: passed
  profile: gcp-cis-gke-1.1
- id: gke-3
  resource: container.googleapis.com/projects/demo1-bad/locations/us-central1/clusters/prod-cluster1
  status: failed
  profile: gcp-cis-gke-1.1
- id: gke-3
  resource: container.googleapis.com/projects/demo1-good/locations/us-central1/clusters/prod-cluster1
  status: failed
  profile: gcp-cis-gke-1.1
- id: gke-4
  resource: container.googleapis.com/projects/demo1-bad/locations/us-central1/clusters/prod-cluster1/nodePools/default-pool
  status: failed
  profile: gcp-cis-gke-1.1
- id: gke-4
  resource: container.googleapis.com/projects/demo1-good/locations/us-central1/clusters/prod-cluster1/nodePools/default-pool
  status: failed
  profile: gcp-cis-gke-1.1
- id: gke-5
  resource: container.googleapis.com/projects/demo1-bad/locations/us-central1/clusters/prod-cluster1/nodePools/default-pool
  status: passed
  profile: gcp-cis-gke-1.1
- id: gke-5
  resource: container.googleapis.com/projects/demo1-good/locations/us-central1/clusters/prod-cluster1/nodePools/default-pool
  status: passed
  profile: gcp-cis-gke-1.1
- id: gke-6
  resource: container.googleapis.com/projects/demo1-bad/locations/us-central1/clusters/prod-cluster1/nodePools/default-pool
  status: passed
  profile: gcp-cis-gke-1.1
- id: gke-6
  resource: container.googleapis.com/projects/demo1-good/locations/us-central1/clusters/prod-cluster1/nodePools/default-pool
  status: passed
  profile: gcp-cis-gke-1.1
- id: darkbit-1
  resource: |
    container.googleapis.com/projects/demo1-bad/locations/us-central1/clusters/prod-cluster1
    to owner via serviceAccount:terraform@demo1-bad.iam.gserviceaccount.com
  status: failed
  profile: gcp-darkbit-best-practices-1.0
- id: darkbit-2
  resource: |
    compute.googleapis.com/projects/demo1-bad/zones/us-central1-a/instances/dev-secrets-manager
    to cluster-admin via serviceAccount:gce-sa@demo1-bad.iam.gserviceaccount.com
  status: failed
  profile: gcp-darkbit-best-practices-1.0
